export const options = [
  { label: "中国", value: "+86", code: "cn", enLabel: "China" },
  { label: "中国香港", value: "+852", code: "cn", enLabel: "Hong Kong" },
  { label: "中国澳门", value: "+853", code: "cn", enLabel: "Macau" },
  { label: "中国台湾", value: "+886", code: "cn", enLabel: "Taiwan" },
  { label: "英国", value: "+44", code: "gb", enLabel: "United Kingdom" },
  { label: "印度", value: "+91", code: "in", enLabel: "India" },
  { label: "德国", value: "+49", code: "de", enLabel: "Germany" },
  { label: "美国", value: "+1", code: "us", enLabel: "United States" },
  { label: "法国", value: "+33", code: "fr", enLabel: "France" },
  { label: "日本", value: "+81", code: "jp", enLabel: "Japan" },
  { label: "韩国", value: "+82", code: "kr", enLabel: "Korea" },
  { label: "加拿大", value: "", code: "ca", enLabel: "Canada" },
  { label: "澳大利亚", value: "+61", code: "au", enLabel: "Australia" },
  { label: "俄罗斯", value: "+7", code: "ru", enLabel: "Russia" },
  { label: "巴西", value: "+55", code: "br", enLabel: "Brazil" },
  { label: "意大利", value: "+39", code: "it", enLabel: "Italy" },
  { label: "西班牙", value: "+34", code: "es", enLabel: "Spain" },
  { label: "墨西哥", value: "+52", code: "mx", enLabel: "Mexico" },
  { label: "南非", value: "+27", code: "za", enLabel: "South Africa" },
  { label: "阿根廷", value: "+54", code: "ar", enLabel: "Argentina" },
  { label: "新加坡", value: "+65", code: "sg", enLabel: "Singapore" },
  { label: "荷兰", value: "+31", code: "nl", enLabel: "Netherlands" },
  { label: "瑞士", value: "+41", code: "ch", enLabel: "Switzerland" },
  { label: "瑞典", value: "+46", code: "se", enLabel: "Sweden" },
  { label: "挪威", value: "+47", code: "no", enLabel: "Norway" },
  { label: "丹麦", value: "+45", code: "dk", enLabel: "Denmark" },
  { label: "芬兰", value: "+358", code: "fi", enLabel: "Finland" },
  { label: "比利时", value: "+32", code: "be", enLabel: "Belgium" },
  { label: "奥地利", value: "+43", code: "at", enLabel: "Austria" },
  { label: "爱尔兰", value: "+353", code: "ie", enLabel: "Ireland" },
  { label: "葡萄牙", value: "+351", code: "pt", enLabel: "Portugal" },
  { label: "新西兰", value: "+64", code: "nz", enLabel: "New Zealand" },
  { label: "泰国", value: "+66", code: "th", enLabel: "Thailand" },
  { label: "马来西亚", value: "+60", code: "my", enLabel: "Malaysia" },
  { label: "印度尼西亚", value: "+62", code: "id", enLabel: "Indonesia" },
  { label: "菲律宾", value: "+63", code: "ph", enLabel: "Philippines" },
  { label: "越南", value: "+84", code: "vn", enLabel: "Vietnam" },
  { label: "土耳其", value: "+90", code: "tr", enLabel: "Turkey" },
  { label: "沙特阿拉伯", value: "+966", code: "sa", enLabel: "Saudi Arabia" },
  {
    label: "阿联酋",
    value: "+971",
    code: "ae",
    enLabel: "United Arab Emirates",
  },
  { label: "以色列", value: "+972", code: "il", enLabel: "Israel" },
  { label: "埃及", value: "+20", code: "eg", enLabel: "Egypt" },
  { label: "尼日利亚", value: "+234", code: "ng", enLabel: "Nigeria" },
  { label: "巴基斯坦", value: "+92", code: "pk", enLabel: "Pakistan" },
  { label: "哥伦比亚", value: "+57", code: "co", enLabel: "Colombia" },
  { label: "智利", value: "+56", code: "cl", enLabel: "Chile" },
  { label: "秘鲁", value: "+51", code: "pe", enLabel: "Peru" },
  { label: "乌克兰", value: "+380", code: "ua", enLabel: "Ukraine" },
  { label: "波兰", value: "+48", code: "pl", enLabel: "Poland" },
  { label: "捷克", value: "+420", code: "cz", enLabel: "Czech Republic" },
  { label: "希腊", value: "+30", code: "gr", enLabel: "Greece" },
  { label: "匈牙利", value: "+36", code: "hu", enLabel: "Hungary" },
];
